services:
  postgres:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
# migrate -database "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable" -path postgresql/migrations up
  server:
    build: .
    restart: "always"
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy

