// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteUploadsByIds(ctx context.Context, ids []uuid.UUID) error
	GetOldInProgressParts(ctx context.Context, createdAt pgtype.Timestamptz) ([]Part, error)
	GetOldInProgressUploads(ctx context.Context, createdAt pgtype.Timestamptz) ([]Upload, error)
	GetUpload(ctx context.Context, id uuid.UUID) (Upload, error)
	GetUploadParts(ctx context.Context, id uuid.UUID) ([]Part, error)
	InsertPart(ctx context.Context, arg InsertPartParams) error
	InsertUpload(ctx context.Context, arg InsertUploadParams) error
	UpdatePartAsDone(ctx context.Context, id uuid.UUID) error
	UpdateUploadAsDone(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
